name: polaris-duels
version: ${project.version}
main: us.polarismc.polarisduels.Main
api-version: '1.21.7'
authors: [putindeer, tmpst, wixent]
description: A Minimalist Duels Plugin for Polaris
website: https://github.com/polaris-mc

commands:
  arena:
    description: Manage arenas
    usage: /arena
    permission: duels.arenamanager
  broadcast:
    description: Broadcast a message to all players
    aliases: [bc]
    permission: duels.admin
  gmc:
    permission: duels.admin
  gmsp:
    permission: duels.admin
  gms:
    permission: duels.admin
  gma:
    permission: duels.admin
  gm:
    aliases: [gamemode]
    permission: duels.admin
  party:
    description: Manage your party
    aliases: [p]
  msg:
    description: Private-message a player
  reply:
    description: Reply to a private-message
    aliases: [r]
  duel:
    description: Sends a duel to a specified player
  debug:
    permission: duels.dev
  test:
    permission: duels.dev
  createvoidworld:
    permission: duels.admin
  world:
    permission: duels.admin
  hex:
    permission: duels.dev
  addalltoparty:
    permission: duels.dev